version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_vol:/mongo_vol

  backend:
    image: tapadinhas/iacd-backend:Assignment3-no-env-var
    ports:
      - "40:80"
    depends_on:
      - 'mongo'
    volumes:
      - backend_vol:/backend_vol 

  frontend:
    image: tapadinhas/iacd-frontend:Assignment1-and-2
    ports:
      - "3000:3000"
    depends_on:
      - 'backend'
    volumes:
      - frontend_vol:/frontend_vol

volumes:
  mongo_vol:
  backend_vol:
  frontend_vol:
