apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: frontend-cont
          image: tapadinhas/iacd-frontend:Assignment1-and-2
          ports:
            - containerPort: 3000
