apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: multi-container-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
