apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: backend-cont
          image: tapadinhas/iacd-backend:Assignment3-no-env-var
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /logs
              name: backend-volume
      volumes:
        - name: backend-volume
          persistentVolumeClaim: 
            claimName: backend-pvc